language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gcc libffi-dev python3-dev
install:
  - pip install -e .
script:
  - python -m unittest
notifications:
  email:
    recipients:
      - maxim.stolyarchuk@gmail.com
    on_success: change
    on_failure: change
